import { Branch } from "@/types/skills"

export const INITIAL_POINTS = 8

export const BRANCHES: Branch[] = [
  {
    id: 'clicker',
    label: 'Кликер',
    emoji: '👊',
    color: '#7C3AED',
    bgColor: '#EDE9FE',
    nodes: [
      {
        id: 'strong_hit',
        emoji: '💪',
        name: 'Сильный удар',
        desc: '+25% к силе клика за уровень',
        maxLevel: 5,
        cost: 1,
      },
      {
        id: 'double_click',
        emoji: '✌️',
        name: 'Двойной клик',
        desc: 'Каждый 10-й клик засчитывается дважды',
        maxLevel: 1,
        cost: 2,
        requires: 'strong_hit',
      },
      {
        id: 'crit_click',
        emoji: '⚡',
        name: 'Крит. клик',
        desc: '+5% шанс нанести x5 урона',
        maxLevel: 3,
        cost: 2,
        requires: 'double_click',
      },
      {
        id: 'combo_master',
        emoji: '🔥',
        name: 'Комбо-мастер',
        desc: 'Комбо даёт x2/x3/x5 вместо x1.5',
        maxLevel: 3,
        cost: 3,
        requires: 'crit_click',
      },
    ],
  },
  {
    id: 'farmer',
    label: 'Фермер',
    emoji: '🌾',
    color: '#059669',
    bgColor: '#D1FAE5',
    nodes: [
      {
        id: 'passive_boost',
        emoji: '🌿',
        name: 'Пассив+',
        desc: '+50% к пассивному доходу за уровень',
        maxLevel: 3,
        cost: 1,
      },
      {
        id: 'autoclicker',
        emoji: '⚙️',
        name: 'Автокликер',
        desc: '-20% интервал между авто-кликами',
        maxLevel: 2,
        cost: 2,
        requires: 'passive_boost',
      },
      {
        id: 'accumulator',
        emoji: '💤',
        name: 'Накопитель',
        desc: 'Офлайн-доход x1.5',
        maxLevel: 1,
        cost: 2,
        requires: 'autoclicker',
      },
      {
        id: 'superfarm',
        emoji: '🌟',
        name: 'Суперферма',
        desc: 'Каждые 10 мин — всплеск пассива x3',
        maxLevel: 1,
        cost: 4,
        requires: 'accumulator',
      },
    ],
  },
  {
    id: 'trader',
    label: 'Торговец',
    emoji: '💰',
    color: '#D97706',
    bgColor: '#FEF3C7',
    nodes: [
      {
        id: 'discount',
        emoji: '🏷️',
        name: 'Скидка',
        desc: '-10% к ценам апгрейдов за уровень',
        maxLevel: 3,
        cost: 1,
      },
      {
        id: 'investor',
        emoji: '📈',
        name: 'Инвестор',
        desc: '+1 к пассиву каждые 100 кликов',
        maxLevel: 3,
        cost: 2,
        requires: 'discount',
      },
      {
        id: 'compound',
        emoji: '🔄',
        name: 'Сложный %',
        desc: '+1%/мин к доходу (макс +50%)',
        maxLevel: 1,
        cost: 3,
        requires: 'investor',
      },
      {
        id: 'monopoly',
        emoji: '👑',
        name: 'Монополия',
        desc: 'Куплено всё → x2 ко всему',
        maxLevel: 1,
        cost: 5,
        requires: 'compound',
      },
    ],
  },
]